version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - static:/app/static
      - media:/app/media
      - ./src:/app
    command: python /app/manage.py runserver
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/dev:/etc/nginx/conf.d
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - backend

volumes:
  static:
  postgres_data:
  media:
