# Generated by Django 4.0.6 on 2024-04-16 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('mobile_number', models.CharField(max_length=255, verbose_name='Сотовый номер')),
                ('work_number', models.CharField(max_length=255, verbose_name='Рабочий номер')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=255, verbose_name='Адрес')),
                ('place', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ('place',),
            },
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('fullname_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fullname_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fullname_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('work_place', models.CharField(max_length=255, verbose_name='Компания')),
                ('work_place_ru', models.CharField(max_length=255, null=True, verbose_name='Компания')),
                ('work_place_en', models.CharField(max_length=255, null=True, verbose_name='Компания')),
                ('work_place_ky', models.CharField(max_length=255, null=True, verbose_name='Компания')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('region_ru', models.CharField(max_length=255, null=True, verbose_name='Регион')),
                ('region_en', models.CharField(max_length=255, null=True, verbose_name='Регион')),
                ('region_ky', models.CharField(max_length=255, null=True, verbose_name='Регион')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Правление',
                'verbose_name_plural': 'Правление',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='jurnal', verbose_name='Баннер')),
                ('file', models.FileField(null=True, upload_to='journals', verbose_name='Файл')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('description_ru', models.TextField(null=True, verbose_name='Информация о компании')),
                ('description_en', models.TextField(null=True, verbose_name='Информация о компании')),
                ('description_ky', models.TextField(null=True, verbose_name='Информация о компании')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Логотип компании')),
                ('image_ru', models.ImageField(null=True, upload_to='partners/', verbose_name='Логотип компании')),
                ('image_en', models.ImageField(null=True, upload_to='partners/', verbose_name='Логотип компании')),
                ('image_ky', models.ImageField(null=True, upload_to='partners/', verbose_name='Логотип компании')),
                ('memorandum', models.FileField(upload_to='memorandums/', verbose_name='Меморандум')),
                ('memorandum_ru', models.FileField(null=True, upload_to='memorandums/', verbose_name='Меморандум')),
                ('memorandum_en', models.FileField(null=True, upload_to='memorandums/', verbose_name='Меморандум')),
                ('memorandum_ky', models.FileField(null=True, upload_to='memorandums/', verbose_name='Меморандум')),
                ('link', models.URLField(verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Меморендум',
                'verbose_name_plural': 'Меморендумы',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Логотип')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на официальный сайт')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('fullname_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fullname_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fullname_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='team')),
                ('choice', models.CharField(choices=[('director', 'Директор'), ('hr', 'Менеджер'), ('empl', 'Другие')], default='empl', max_length=255, verbose_name='Выбор Должности в jia')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('description', models.TextField(blank=True, default=' ', null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, default=' ', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, default=' ', null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, default=' ', null=True, verbose_name='Описание')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='about.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Дирекция',
                'verbose_name_plural': 'Дирекция',
            },
        ),
    ]
