# Generated by Django 4.0.6 on 2024-05-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='work_number',
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(default='', upload_to='contact', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='about.branch', verbose_name='Филиал'),
        ),
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='about.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='about.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchCellular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Сотовые')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellulars', to='about.branch')),
            ],
        ),
    ]
