# Generated by Django 4.0.4 on 2022-05-29 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('mobile_number', models.CharField(max_length=255, verbose_name='Сотовый номер')),
                ('work_number', models.CharField(max_length=255, verbose_name='Рабочий номер')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='BusinessSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на официальный источник')),
                ('banner', models.ImageField(null=True, upload_to='business_support', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Поддержка бизнеса',
                'verbose_name_plural': 'Поддержка бизнеса',
            },
        ),
        migrations.CreateModel(
            name='CPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('mobile_number', models.CharField(max_length=255, verbose_name='Сотовый номер')),
                ('work_number', models.CharField(max_length=255, verbose_name='Рабочий номер')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'ЦПП',
                'verbose_name_plural': 'ЦПП',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('file', models.FileField(null=True, upload_to='journals', verbose_name='Файл')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название рубрики')),
            ],
            options={
                'verbose_name': 'Рубрика новостей',
                'verbose_name_plural': 'Рубрики новостей',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Логотип')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на официальный сайт')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел фото',
                'verbose_name_plural': 'Разделы фото',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('file', models.FileField(null=True, upload_to='reports', verbose_name='Файл')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Логотип')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на официальный сайт')),
                ('category', models.CharField(choices=[('a', 'A'), ('b', 'B')], default='a', max_length=1, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Резидент',
                'verbose_name_plural': 'Резиденты',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(null=True, verbose_name='facebook')),
                ('whatsapp', models.URLField(null=True, verbose_name='whatsapp')),
                ('instagram', models.URLField(null=True, verbose_name='instagram')),
                ('telegram', models.URLField(null=True, verbose_name='telegram')),
                ('youtube', models.URLField(null=True, verbose_name='youtube')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Дирекция',
                'verbose_name_plural': 'Дирекция',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_gallery', verbose_name='Изображение')),
                ('main', models.BooleanField(default=False, verbose_name='Главная картинка')),
                ('tag', models.ManyToManyField(to='content.photogallerytag', verbose_name='Разделы')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_gallery', verbose_name='Изображение')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новости',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.newstag', verbose_name='Рубрика'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events', verbose_name='Изображение')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Мероприятиe',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
