# Generated by Django 4.0.5 on 2022-06-28 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_news_tag_alter_newsimage_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('-id',), 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-id',), 'verbose_name': 'Мероприятиe', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ('-id',), 'verbose_name': 'Изображение новости', 'verbose_name_plural': 'Изображения новости'},
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'ordering': ('-id',), 'verbose_name': 'Рубрика новостей', 'verbose_name_plural': 'Рубрики новостей'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ('-id',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-id',), 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='team'),
            preserve_default=False,
        ),
    ]
