# Generated by Django 4.0.6 on 2024-05-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_residentjia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcellular',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactemail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactphone',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactCellular',
        ),
        migrations.DeleteModel(
            name='ContactEmail',
        ),
        migrations.DeleteModel(
            name='ContactPhone',
        ),
    ]
