# Generated by Django 4.0.5 on 2022-06-30 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_teammember_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='choice',
            field=models.CharField(choices=[('Годовые отчеты', 'Годовые отчеты'), ('Квартальные отчеты', 'Квартальные отчеты')], default=django.utils.timezone.now, max_length=255, verbose_name='Выбор'),
            preserve_default=False,
        ),
    ]
