# Generated by Django 4.0.5 on 2022-06-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_report_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('category', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='a', max_length=1, verbose_name='Категория')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена за резиденство')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип')),
                ('pdf_file', models.FileField(upload_to='pdf', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Cтать резидентом',
                'verbose_name_plural': 'Cтать резидентом',
            },
        ),
        migrations.CreateModel(
            name='MemberShipPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priveleges', to='content.membership')),
            ],
            options={
                'verbose_name': 'Привилегии для резидента',
                'verbose_name_plural': 'Привилегии для резидента',
            },
        ),
    ]
