# Generated by Django 4.0.5 on 2022-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_membership_membershipprivileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Категория'),
        ),
    ]
