# Generated by Django 4.0.5 on 2022-06-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главный в команде'),
        ),
    ]
