# Generated by Django 4.0.5 on 2022-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_teammember_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('kg', 'Kg')], default='ru', max_length=2, verbose_name='Язык')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='team')),
                ('main', models.BooleanField(default=False, verbose_name='Главный в команде')),
                ('work_place', models.CharField(max_length=255, verbose_name='Филиал')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='main',
        ),
        migrations.AddField(
            model_name='teammember',
            name='choice',
            field=models.CharField(choices=[('director', 'Директор'), ('hr', 'Менеджер'), ('empl', 'Другие')], default='empl', max_length=255, verbose_name='Должность в jia'),
        ),
    ]
