# Generated by Django 4.0.5 on 2022-06-30 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_governingbody_remove_teammember_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governingbody',
            options={'verbose_name': 'Правление', 'verbose_name_plural': 'Правление'},
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('Взаимодействие с государственными органами и членство в советах', 'Gos'), ('Меморандумы', 'Mem')], default=django.utils.timezone.now, max_length=255, verbose_name='Выбор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='choice',
            field=models.CharField(choices=[('director', 'Директор'), ('hr', 'Менеджер'), ('empl', 'Другие')], default='empl', max_length=255, verbose_name='Выбор Должности в jia'),
        ),
    ]
