# Generated by Django 4.0.5 on 2022-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_governingbody_options_partner_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('государственными', 'State'), ('Меморандумы', 'Memorandums')], max_length=255, verbose_name='Выбор'),
        ),
    ]
