# Generated by Django 4.0.5 on 2022-06-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_partner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('state', 'State'), ('memorandums', 'Memorandums')], max_length=255, verbose_name='Выбор'),
        ),
    ]
