# Generated by Django 4.0.5 on 2022-07-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_partner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='content.branch', verbose_name='Филиал'),
        ),
    ]
