# Generated by Django 4.0.5 on 2022-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_teammember_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='language',
        ),
        migrations.RemoveField(
            model_name='businesssupport',
            name='language',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='language',
        ),
        migrations.RemoveField(
            model_name='cpp',
            name='language',
        ),
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.RemoveField(
            model_name='governingbody',
            name='language',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='language',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='language',
        ),
        migrations.RemoveField(
            model_name='membershipprivileges',
            name='language',
        ),
        migrations.RemoveField(
            model_name='news',
            name='language',
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='language',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='language',
        ),
        migrations.RemoveField(
            model_name='photogallerytag',
            name='language',
        ),
        migrations.RemoveField(
            model_name='report',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='language',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='language',
        ),
        migrations.AddField(
            model_name='branch',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='businesssupport',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='businesssupport',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='businesssupport',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='businesssupport',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='email_en',
            field=models.EmailField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='email_ru',
            field=models.EmailField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='mobile_number_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Сотовый номер'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='mobile_number_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Сотовый номер'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='work_number_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочий номер'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='work_number_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочий номер'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='fullname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='fullname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='work_place_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='work_place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='membershipprivileges',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='membershipprivileges',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название рубрики'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название рубрики'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='photogallerytag',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='photogallerytag',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='resident',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='resident',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='resident',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='resident',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='fullname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='fullname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
