# Generated by Django 4.0.5 on 2022-07-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_branch_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='businesssupport',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='businesssupport',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='email_ky',
            field=models.EmailField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='mobile_number_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Сотовый номер'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='work_number_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочий номер'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='fullname_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='position_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='work_place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='membershipprivileges',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название рубрики'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='photogallerytag',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='resident',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='resident',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='fullname_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
