# Generated by Django 4.0.6 on 2022-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_branch_address_ky_branch_title_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True, verbose_name='URL представление'),
        ),
    ]
