# Generated by Django 4.0.6 on 2022-07-08 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_news_description_alter_news_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('-id',), 'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='jurnal', verbose_name='Баннер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
