# Generated by Django 4.0.6 on 2022-07-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_news_facebook_news_instagram_news_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentJia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Резиденты Jia',
                'verbose_name_plural': 'Резиденты Jia',
            },
        ),
    ]
