# Generated by Django 4.0.6 on 2022-07-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_residentjia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssupport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businesssupport',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='businesssupport',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='businesssupport',
            name='description_ru',
        ),
    ]
