# Generated by Django 4.0.6 on 2022-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_remove_businesssupport_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('banner', models.ImageField(null=True, upload_to='business_support', verbose_name='Баннер')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на официальный сайт')),
            ],
            options={
                'verbose_name': 'Main Page',
                'verbose_name_plural': 'Main Page',
            },
        ),
    ]
