# Generated by Django 4.0.6 on 2022-07-10 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_mainpagebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governingbody',
            name='image',
        ),
        migrations.RemoveField(
            model_name='governingbody',
            name='main',
        ),
        migrations.AddField(
            model_name='governingbody',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='governingbody',
            name='work_place',
            field=models.CharField(max_length=255, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='governingbody',
            name='work_place_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='governingbody',
            name='work_place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='governingbody',
            name='work_place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Компания'),
        ),
    ]
