# Generated by Django 4.0.6 on 2022-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_governingbody_region_en_governingbody_region_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='action_plane', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'План мероприятий',
                'verbose_name_plural': 'План мероприятий',
                'ordering': ('-id',),
            },
        ),
    ]
