# Generated by Django 4.0.6 on 2022-07-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_actionplane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='news',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='news',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='news',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='news',
            name='whatsapp',
        ),
    ]
