# Generated by Django 4.0.6 on 2022-08-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_advertising_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Address')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Footer Info',
                'verbose_name_plural': 'Footer Info',
            },
        ),
        migrations.CreateModel(
            name='FooterPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('footer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='content.footerinfo')),
            ],
            options={
                'verbose_name': 'Footer Info',
                'verbose_name_plural': 'Footer Info',
            },
        ),
    ]
