# Generated by Django 4.0.6 on 2022-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_alter_teammember_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplane',
            name='image_en',
            field=models.ImageField(null=True, upload_to='action_plane', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='actionplane',
            name='image_ky',
            field=models.ImageField(null=True, upload_to='action_plane', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='actionplane',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='action_plane', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
        migrations.DeleteModel(
            name='PhotoGalleryTag',
        ),
    ]
