# Generated by Django 4.0.6 on 2022-08-31 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_report_file_en_report_file_ky_report_file_ru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CPP',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo_gallery', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
