# Generated by Django 4.0.6 on 2022-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_delete_cpp_remove_newsimage_news_delete_resident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='photo_news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Картинки Новостей',
                'verbose_name_plural': 'Картинки Новостей',
                'ordering': ('-id',),
            },
        ),
    ]
