# Generated by Django 4.0.6 on 2022-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
    ]
