# Generated by Django 4.0.6 on 2022-09-26 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_teammember_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_descriotion',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Main Описание'),
            preserve_default=False,
        ),
    ]
