# Generated by Django 4.0.6 on 2022-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_news_main_descriotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='residentjia',
            name='file_en',
            field=models.FileField(null=True, upload_to='file', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='residentjia',
            name='file_ky',
            field=models.FileField(null=True, upload_to='file', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='residentjia',
            name='file_ru',
            field=models.FileField(null=True, upload_to='file', verbose_name='PDF'),
        ),
    ]
