# Generated by Django 4.0.6 on 2022-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_delete_sociallink_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governingbody',
            options={'ordering': ('order',), 'verbose_name': 'Правление', 'verbose_name_plural': 'Правление'},
        ),
        migrations.AddField(
            model_name='governingbody',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
