# Generated by Django 4.0.6 on 2023-01-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_alter_governingbody_options_governingbody_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('place',), 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AddField(
            model_name='branch',
            name='place',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='main_descriotion_en',
            field=models.TextField(null=True, verbose_name='Main Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='main_descriotion_ky',
            field=models.TextField(null=True, verbose_name='Main Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='main_descriotion_ru',
            field=models.TextField(null=True, verbose_name='Main Описание'),
        ),
    ]
