# Generated by Django 4.0.6 on 2023-01-16 11:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_alter_branch_options_branch_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='photo_gallery', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_descriotion',
            field=models.TextField(blank=True, null=True, verbose_name='Main Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_descriotion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Main Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_descriotion_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Main Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_descriotion_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Main Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
