# Generated by Django 4.0.6 on 2023-07-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents', verbose_name='Документ')),
                ('file_ru', models.FileField(null=True, upload_to='documents', verbose_name='Документ')),
                ('file_en', models.FileField(null=True, upload_to='documents', verbose_name='Документ')),
                ('file_ky', models.FileField(null=True, upload_to='documents', verbose_name='Документ')),
                ('image', models.ImageField(upload_to='document_images', verbose_name='Изображение')),
                ('image_ru', models.ImageField(null=True, upload_to='document_images', verbose_name='Изображение')),
                ('image_en', models.ImageField(null=True, upload_to='document_images', verbose_name='Изображение')),
                ('image_ky', models.ImageField(null=True, upload_to='document_images', verbose_name='Изображение')),
                ('description', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Комментарий')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Комментарий')),
                ('description_ky', models.CharField(max_length=255, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Положение',
                'verbose_name_plural': 'Положения',
            },
        ),
    ]
