# Generated by Django 4.0.6 on 2023-07-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('description_ru', models.TextField(null=True, verbose_name='Информация о компании')),
                ('description_en', models.TextField(null=True, verbose_name='Информация о компании')),
                ('description_ky', models.TextField(null=True, verbose_name='Информация о компании')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Логотип компании')),
                ('image_ru', models.ImageField(null=True, upload_to='partners/', verbose_name='Логотип компании')),
                ('image_en', models.ImageField(null=True, upload_to='partners/', verbose_name='Логотип компании')),
                ('image_ky', models.ImageField(null=True, upload_to='partners/', verbose_name='Логотип компании')),
                ('memorandum', models.FileField(upload_to='memorandums/', verbose_name='Меморандум')),
                ('memorandum_ru', models.FileField(null=True, upload_to='memorandums/', verbose_name='Меморандум')),
                ('memorandum_en', models.FileField(null=True, upload_to='memorandums/', verbose_name='Меморандум')),
                ('memorandum_ky', models.FileField(null=True, upload_to='memorandums/', verbose_name='Меморандум')),
            ],
        ),
    ]
