# Generated by Django 4.0.6 on 2023-07-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_partnership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnership',
            options={'verbose_name': 'Меморендум', 'verbose_name_plural': 'Меморендумы'},
        ),
    ]
