# Generated by Django 4.0.6 on 2023-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_alter_partnership_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='district_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за резиденствие в регионах'),
        ),
    ]
