# Generated by Django 4.0.6 on 2023-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_partnership_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Логотип')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на официальный сайт')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
