# Generated by Django 4.0.6 on 2023-07-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_state_delete_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='email',
        ),
        migrations.CreateModel(
            name='FooterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('footer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='content.footerinfo')),
            ],
            options={
                'verbose_name': 'Footer Info',
                'verbose_name_plural': 'Footer Info',
            },
        ),
    ]
