# Generated by Django 4.0.6 on 2023-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='icon',
            field=models.CharField(default='', max_length=127, verbose_name='Иконка (https://remixicon.com)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(upload_to='organization/', verbose_name='Картинка организации'),
        ),
    ]
